### ISSUE TITLE
Examples of russell to solve 3D Poisson equations

### ISSUE THREAD

**Issue by supernova4869** [cpmech/russell#107]
I want to solve the 3D Poisson-Boltzmann equation like $$\nabla^2 \phi - \kappa^2 \phi = 4 \pi \rho_f / \epsilon$$ with the boundary contitions $$\phi (\infty) = 0$$ could the russell handle this problem? I saw that the PDE example was for 2D Laplace equation.

**Comment by cpmech** [comment]
Hi, unfortunately, Russell doesn't have a solver for such a problem.

The goal for the 2D Laplace operator in the `russell_ode` crate is to test the _ODE_ solvers only. It may be converted to a 3D solver based on Finite Differences, nonetheless.

Russell aims to provide the foundation tools for implementing PDE solvers, but not implement them (because there are many problem types and many solution methods!).

As another example, it is possible to use the foundation tools of the `russell_lab` crate (within the `algo` module) to develop Spectral Collocation methods for multidimensional PDEs. There is a [1D example here](https://github.com/cpmech/russell/blob/main/russell_lab/examples/algo_lorene_1d_pde_spectral_collocation.rs) that may serve as a basis to implement a 3D solver.

**Comment by supernova4869** [comment]
Thank you. I will try to develop it as an extend work.
