### ISSUE TITLE
Make solvers clonable for caching purposes

### ISSUE THREAD

**Issue by soudy** [cpmech/russell#69]
Hi,

First of all, thanks for creating this library! It has been a joy to use for my project.

In my project, I would like to precompute some sparse matrices and their factorization to reuse them later to solve for different `b`s. In turn, something I would like to do something like this at the beginning of my program:

```rust
let mut mat = self.create_sparse_diffusion_laplacian(params);

let mut solver = SolverUMFPACK::new().unwrap();
solver.factorize(&mut mat, None).unwrap();

// same to some cache
CACHE.push((solver, mat))
```

And then later, in some other function with access to cache, load the factorized solver:
```rust
let mut solver = CACHE.get(i).clone(); // this currently doesn't work --- SolverUMFPACK doesn't implement Clone trait

let mut b = populate_b();
let mut x = Vector::new(params.n_dev_cells);

solver.solve(&mut x, &mat, &b, false).unwrap();
```

However, at the moment I cannot clone the solver as the `Clone` trait is not implemented. I am not too familiar with Rust yet, or its FFI, but would it be possible to support this kind of behaviour? Or is there some other way to achieve this?

Thanks in advance!

**Comment by cpmech** [comment]
Hello.

This request is indeed interesting. And I was about to take a look at it. However, we cannot clone the solver!

The solver holds a pointer to an underlying C structure. And this cannot be copied. See this line: https://github.com/cpmech/russell/blob/a61247268c8b96b350c3acf5aa9e77fc48242917/russell_sparse/src/solver_umfpack.rs#L59

I understand that your CACHE is a global static variable, right? So, we cannot save `solver` in the CACHE.

I guess the way to go is to pass a reference to `solver` from one function to another.

Cheers.

**Comment by cpmech** [comment]
Hi, I've implemented `Clone` for COO, CSC, CSR and SparseMatrix: [9cdd778](https://github.com/cpmech/russell/commit/9cdd778a5d002d81c13a38a37aba4f22a9d2d27c)

I hope it helps.

**Comment by soudy** [comment]
Brilliant, thanks @cpmech!

**Comment by cpmech** [comment]
I was thinking about this problem and did some research on how to "parallelize this rust code."

The source of the problem is the use of memory allocated on the C-side. For instance, MUMPS and UMFPACK allocate their own structures, and the best approach (used in `russell_sparse`) is to keep "C-things" on the "C-side." Therefore, we cannot send data (e.g., Solvers) from thread to thread on the "Rust-side."

Noting that the concurrency/multithreads model in Rust (and probably in other multithread solutions) does require data to be sent and synced (traits `Send` and `Sync`), we cannot do this on Rust.

Then, I thought about using the "good old" MPI (message-passing interface) paradigm. With MPI, we can spawn multiple copies of the simulation to different processors (even at different machines connected with ethernet). This is the "classical" HPC (high-performance computing) strategy. Note that we can still use threads within each process.

I did some experiments yielding promising results. I also implemented the [msgpass package](https://github.com/cpmech/msgpass) to assist us. For instance, we can solve multiple linear systems in parallel with a code similar to the one below:

```rust
// initialize the MPI engine
mpi_init_thread(MpiThread::Serialized)?;

// allocate MPI communicator and determine this processor's rank
let mut comm = Communicator::new()?;
let rank = comm.rank()?;

// create coefficient matrix
let (fdm, mut mat) = create_discrete_laplacian(opt.nx, opt.nx, one_based);

// allocate linear solver
let mut solver = LinSolver::new(genie)?;

// perform the factorization
solver.actual.factorize(&mut mat, None)?;

// allocate the solution vector
let mut x = Vector::new(dim);

// solve many times with increasing multipliers
const MULTIPLIERS: &[f64] = &[1.0, 2.0, 5.0, 10.0, 100.0];
for multiplier in MULTIPLIERS {
    let b = populate_rhs_vector(&fdm, *multiplier);
    solver.actual.solve(&mut x, &mat, &b, false)?;

    // use MPI here to communicate the results among the processors
}
```

[See the full code here](https://github.com/cpmech/solve_many_linsys)

The linear systems are entirely independent and thus should give us ideal performance. Nonetheless, using shared resources (e.g., memory) may lead to performance loss. For instance, UMFPACK requires too much memory, and the performance is not ideal when using 8 cores (the "performance" cores of my Intel i9). The performance with MUMPS is better.

Some results (size is the number of processes; the number of threads within each process is fixed to 1):

**Mumps** (see [log-mumps.txt](https://github.com/cpmech/solve_many_linsys/blob/main/log-mumps.txt))

```text
size = 1, nx = 1000, dim = 1000000, genie = Mumps
elapsed time ~ 5.149872364s

size = 4, nx = 1000, dim = 1000000, genie = Mumps
elapsed time ~ 5.635183616s

size = 8, nx = 1000, dim = 1000000, genie = Mumps
elapsed time ~ 6.014376048s

size = 24, nx = 1000, dim = 1000000, genie = Mumps
elapsed time ~ 11.618588898s
```

**Umfpack:** (see [log-umfpack.txt](https://github.com/cpmech/solve_many_linsys/blob/main/log-umfpack.txt))

```text
size = 1, nx = 1000, dim = 1000000, genie = Umfpack
elapsed time ~ 6.474512896s

size = 4, nx = 1000, dim = 1000000, genie = Umfpack
elapsed time ~ 8.152130192s

size = 8, nx = 1000, dim = 1000000, genie = Umfpack
elapsed time ~ 11.103594675s

size = 24, nx = 1000, dim = 1000000, genie = Umfpack
elapsed time ~ 29.423033658s
```

I hope it helps.

**Comment by cpmech** [comment]
It appears that it's possible to make the solvers clonable!

I've used the ["trick" described here](https://stackoverflow.com/questions/50258359/can-a-struct-containing-a-raw-pointer-implement-send-and-be-ffi-safe)

Now, we can `impl Send for Solver`, e.g.: https://github.com/cpmech/russell/blob/f90be94a95f9daf8981670e8c7c80870713f4f6f/russell_sparse/src/solver_umfpack.rs#L23

As an example, the (new) crate `russell_ode` [factorizes two systems (one real and one complex) concurrently](https://github.com/cpmech/russell/blob/main/russell_ode/src/radau5.rs) using the following code:

```rust
fn factorize_concurrently(&mut self) -> Result<(), StrError> {
    thread::scope(|scope| {
        let handle_real = scope.spawn(|| {
            self.solver_real
                .actual
                .factorize(&mut self.kk_real, self.params.newton.lin_sol_params)
                .unwrap();
        });
        let handle_comp = scope.spawn(|| {
            self.solver_comp
                .actual
                .factorize(&mut self.kk_comp, self.params.newton.lin_sol_params)
                .unwrap();
        });
        let err_real = handle_real.join();
        let err_comp = handle_comp.join();
        if err_real.is_err() && err_comp.is_err() {
            Err("real and complex factorizations failed")
        } else if err_real.is_err() {
            Err("real factorizations failed")
        } else if err_comp.is_err() {
            Err("complex factorizations failed")
        } else {
            Ok(())
        }
    })
}
```

In this case, it is important to use the `thread::scope(|scope| {}` approach.

Also, only UMFPACK works concurrently (MUMPS is not thread-safe).
